name: rsync to sourceforge.net
on:
  workflow_dispatch:
jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup key
      run: |
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
      env:
        SSH_KEY: ${{ secrets.RSYNC_KEY }}
    - name: rsync
      run: |
         rsync -avPzc --delete --exclude=.git --exclude=.github -e 'ssh -o "StrictHostKeyChecking=no"' . jmb@web.sourceforge.net:/home/project-web/linuxjm/htdocs/
